### ISSUE TITLE
Replace $ with a more filename-friendly symbol?

### ISSUE THREAD

**Issue by stela5** [taitulism/Bootstruct#41]
Your choice of `$` for your hooks filename prefix is problematic on Linux (and potentially other OSs).  For example, `touch $in.js` doesn't work (creates a `.js` file instead.  I can escape the dollar sign as a workaround but any thoughts of refactoring with a more friendly symbol, like `~`?

https://www.mtu.edu/umc/services/digital/writing/characters-avoid/

**Comment by taitulism** [comment]
Thanks for opening this important issue. I wasn't aware of that since I don't have much xp with Linux, tests worked fine on my Ubuntu vm.

For future readers, the reason is that on Linux the $ sign is a prefix for accessing variables.
As @stela5 mentioned, the $ could be escaped with a backslash as a workaround e.g. `touch \$in.js`.

After playing with the tilde (~) as you suggested, although it's better than $, I find it not ideal as CLI completion doesn't works for tilde~ (it does work if you escape the tilde but that's also unfriendly)

What do you say about _underscore? `touch _in.js`

**Comment by taitulism** [comment]
underscore it is.

_in.js
_out.js
_etc.
